name: pangeoml
channels:
  - conda-forge
  - rapidsai-nightly
dependencies:
  # base image 
  - python=3.7
  - jupyterlab=1.2
  - jupyterhub=1.0
  - jupyter-server-proxy=1.2
  - nbgitpuller=0.8
  - dask=2.9
  - distributed=2.9
  - dask-kubernetes=0.10
  - dask-gateway=0.6
  - dask-labextension=1
  - tornado=6
  - bokeh=1.4
  - python-graphviz=0.13
  - pip=19.3
  # core scipy packages
  - numpy
  - scipy
  - matplotlib
  - pandas
  - xarray>=0.14.0
  - sparse
  # data science stuff
  - scikit-image
  - scikit-learn
  - dask-ml
  - tensorflow-gpu
  - keras-gpu
  - pytorch-cpu
  - cupy
  - cudf
  - rmm
  - cuspatial
  # pyviz
  - holoviews
  - panel
  - geoviews
  - hvplot
  - geoviews
  - datashader
  # geospatial
  - cartopy
  - geopandas
  - rasterio
  - netcdf4
  - h5py
  - h5netcdf
  - regionmask
  - rio-cogeo
  # intake-related
  - intake
  - intake-xarray
  - intake-esm
  # zarr-related
  - zarr
  - numcodecs
  - python-blosc
  - lz4
  - gcsfs
  - s3fs
  - tiledb-py
  # xarray-related
  - xgcm
  - xrft
  - pip:
    - jupyterlab-nvdashboard
